receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  logging/traces: {}
  logging/logs: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging/traces]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging/logs]
