receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  resource:
    attributes:
      - key: service.name
        value: fastapi-service
        action: insert

exporters:
  debug/traces:
    verbosity: detailed
  debug/logs:
    verbosity: detailed
  debug/metrics:
    verbosity: detailed
  otlp/aspecto:
    endpoint: otelcol.aspecto.io:4317
    headers:
      Authorization: 0eace6c8-19dd-4ef1-95cb-9244d3be3256

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug/traces, otlp/aspecto]
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug/logs]
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug/metrics]
